name: "Publish latest"
on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: '${{ github.repository_owner }}'
          password: '${{ secrets.GITHUB_TOKEN }}'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - run: docker pull --platform amd64 ghcr.io/h2eproject/bellows2mqtt:latest
      - run: docker pull --platform arm64 ghcr.io/h2eproject/bellows2mqtt:latest
      - run: docker buildx build --platform amd64,arm64 --push -t ghcr.io/h2eproject/bellows2mqtt:'${{ github.sha }}' .
      - run: docker buildx build --platform amd64,arm64 --push -t ghcr.io/h2eproject/bellows2mqtt:${GITHUB_REF##*/} .
      - run: docker buildx build --platform amd64,arm64 --push -t ghcr.io/h2eproject/bellows2mqtt:latest .
        if: ${{ github.ref == 'refs/heads/main'}}